// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALYn8M4Q1UnsIPl9bFYKUk2G9dosmzKfk',
    appId: '1:548925235872:web:1a5072e124116e06ce1fc5',
    messagingSenderId: '548925235872',
    projectId: 'get-rice',
    authDomain: 'get-rice.firebaseapp.com',
    storageBucket: 'get-rice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN8Prxr5CqZgd13QgcAzTqJAz-8XAlBXk',
    appId: '1:548925235872:android:6535a812452c5b83ce1fc5',
    messagingSenderId: '548925235872',
    projectId: 'get-rice',
    storageBucket: 'get-rice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQcwLJ1puVLxlG_CsV4jiYxFB16_rr5y8',
    appId: '1:548925235872:ios:8ec4ae666dd42cb5ce1fc5',
    messagingSenderId: '548925235872',
    projectId: 'get-rice',
    storageBucket: 'get-rice.appspot.com',
    iosBundleId: 'com.example.getRice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQcwLJ1puVLxlG_CsV4jiYxFB16_rr5y8',
    appId: '1:548925235872:ios:da3b7c8fedd0466dce1fc5',
    messagingSenderId: '548925235872',
    projectId: 'get-rice',
    storageBucket: 'get-rice.appspot.com',
    iosBundleId: 'com.example.getRice.RunnerTests',
  );
}
